withme58/peephole-front

src/Router.jsx, src/components/Login/LoginForm.jsx, src/components/Main/SendQuestionModal.jsx, src/pages/Signup/SignupPage.jsx
=> 💄 style: 아이콘, 제목 스타일 적용

src/Router.jsx, src/components/FriendList/AddFriendModal.jsx, src/components/FriendList/DeleteConfirmationModal.jsx, src/components/FriendList/ListForm.jsx, src/pages/FriendList/FriendListPage.jsx, src/pages/ReplyQuestion/ReplyQuestionPage.jsx
- 친구 목록 페이지 레이아웃 완성했어요
- 일단 mock데이터로 추가 삭제 가능하긴 해요
- [
어때요?
>
=> ✨ feat: 친구 목록 페이지 레이아웃 완성

src/components/ReplyQuestion/ReplyForm.jsx, src/pages/ReplyQuestion/ReplyQuestionPage.jsx
=> ✨ feat: 질문 대답하기 레이아웃 완성

src/components/Login/LoginFind.jsx, src/components/Login/LoginForm.jsx, src/components/Login/LoginHeader.jsx, src/components/Login/LoginToSignUp.jsx, src/components/userMolcules/Input.jsx, src/pages/Login/LoginPage.jsx, src/styles/GlobalStyle.js
> 스타일 수정중입니당 배경색 public/image에 넣어두었어용
아직 폰트는 설치 안했습니당
=> 💄 style: 로그인 디자인 수정

src/components/Library/OpenBook.jsx
=> library 모달 디자인 수정

src/components/Library/LibraryBook.jsx, src/components/Library/OpenBook.jsx, src/pages/Library/LibraryPage.jsx
=> library 수정본

src/components/MyPage/MyPageForm.jsx, src/index.js, src/styles/GlobalStyle.js
=> 💄 배경 width 조정

src/components/FriendList/InvitationConfirmationModal.jsx, src/components/FriendList/ListForm.jsx
=> 친구초대 수락,거절 추가

src/components/FriendList/ListForm.jsx, src/components/FriendList/ListHeader.jsx, src/pages/FriendList/FriendListPage.jsx, src/pages/MyPage/MyPage.jsx, src/pages/ReplyQuestion/ReplyQuestionPage.jsx
=> Feature/friend list ui 업데이트

src/components/Login/LoginForm.jsx, src/components/Main/TodayInterview.jsx, src/components/Molcules/Header.jsx, src/components/Signup/SignupForm.jsx, src/components/Signup/SignupHeader
=> HOTFIX: 삭제된 코드 복구 및 충돌해결

src/components/Signup/SignupForm.jsx
=> 📝 docs: 코드 복구

src/components/MyPage/MyPageForm.jsx, src/pages/MyPage/MyPage.jsx
=> Feature/mypage 마이페이지 쫌쫌따리 추가 변경

src/components/Login/LoginForm.jsx, src/components/Signup/SignupForm.jsx, src/store/useUserStore.jsx
=> 🐛 fix: 로그인 회원가입 api 연결

package-lock.json, package.json, src/api/axios.jsx, src/components/Login/LoginForm.jsx
user-storage는 무시하시길.. 테스트 중입니다
=> 🐛 fix: 엑세스, 리프레시 토큰 로컬스토리지에 저장

.gitignore, src/components/FriendList/ListForm.jsx, src/components/FriendList/ListHeader.jsx, src/components/MyPage/MyPageForm.jsx, src/components/ReplyQuestion/ReplyForm.jsx, src/pages/FriendList/FriendListPage.jsx, src/pages/MyPage/MyPage.jsx, src/pages/ReplyQuestion/ReplyQuestionPage.jsx
=> ui 스타일들 수정되었쑵니다

src/api/axios.jsx, src/components/CalculateDate/CalculateDate.jsx, src/components/Login/LoginForm.jsx, src/components/Main/SendQuestionModal.jsx, src/components/Main/TodayInterview.jsx, src/components/Molcules/Input.jsx
=> 🐛 fix: 토큰 에러 수정

src/components/CalculateDate/CalculateDate.jsx, src/components/Main/TodayInterview.jsx
=> 🐛 fix: api 로직 작성

src/api/axios.jsx, src/components/Login/LoginForm.jsx, src/components/Main/SendQuestionModal.jsx, src/components/Main/TodayInterview.jsx, src/utils/DdayCalculator.jsx
=> 🐛 fix: 자잘한 오류 수정

src/components/Library/OpenBook.jsx, src/pages/Library/LibraryPage.jsx
=> Feature library

src/components/FriendList/AddFriendModal.jsx, src/components/FriendList/InvitationConfirmationModal.jsx, src/components/FriendList/ListForm.jsx, src/components/Login/LoginForm.jsx, src/components/MyPage/MyPageForm.jsx
=> 마이페이지, 친구 목록 페이지 api 연결 했습니다

src/components/FriendList/ListForm.jsx
=> 🚑 HOTFIX: 친구 리스트 맵핑 수정

src/components/FriendList/InvitationConfirmationModal.jsx
=> 🚑 HOTFIX: 초대받은 목록 리스트 잘 뜸!!!!!!!!

src/components/ReplyQuestion/QuestionAllForm.jsx, src/components/ReplyQuestion/ReplyForm.jsx, src/pages/ReplyQuestion/QuestionAll.jsx
=> ✨ 질문 응답 페이지 api 연결 완!

src/components/Main/SendQuestionModal.jsx
=> 🐛 fix: 보내면 홈으로 가게 수정

src/components/FriendList/InvitationConfirmationModal.jsx, src/components/FriendList/ListForm.jsx, src/components/FriendList/ListHeader.jsx, src/components/ReplyQuestion/ReplyForm.jsx
=> 내 api 연결 완료~

src/components/FriendList/AddFriendModal.jsx, src/components/FriendList/ListForm.jsx, src/components/FriendList/ListHeader.jsx, src/components/ReplyQuestion/ReplyForm.jsx, src/pages/Login/LoginPage.jsx, src/pages/MyPage/MyPage.jsx
=> 🐛 버그 수정했어용

src/api/axios.jsx
=> 코드 리팩토링 및 로직 수정

public/index.html, src/components/Library/LibraryBook.jsx, src/components/Library/OpenBook.jsx, src/pages/Library/LibraryPage.jsx
=> 폰트 추가 html 추가및 라이브러리 수정

src/components/Library/LibraryBook.jsx, src/components/Library/OpenBook.jsx, src/pages/Library/LibraryPage.jsx
=> library 모달 수정 및 여러가지..

src/components/Landing/LandingMain.jsx, src/pages/Landing/LandingPage.jsx
=> 💄 style: 랜딩페이지 퍼블리싱

src/components/CalculateDate/CalculateDate.jsx, src/components/Landing/LandingHeader.jsx, src/components/Login/LoginForm.jsx, src/components/Main/Interview/FailModal.jsx, src/components/Main/Interview/SendQuestionModal.jsx, src/components/Main/Interview/SuccessModal.jsx, src/components/Main/Interview/TodayInterview.jsx, src/components/Molcules/Header.jsx, src/components/Molcules/Input.jsx, src/components/Molcules/MainHeader.jsx, src/components/Signup/SignupForm.jsx, src/pages/Login/LoginPage.jsx, src/pages/Signup/SignupPage.jsx
=> 🐛 fix: 실패하면 메인으로 레츠꼬

src/components/FriendList/DeleteConfirmationModal.jsx, src/components/FriendList/FriendListHeader.jsx, src/components/FriendList/InvitationConfirmationModal.jsx, src/components/FriendList/ListForm.jsx, src/components/FriendList/ListHeader.jsx, src/pages/FriendList/FriendListPage.jsx, src/pages/MyPage/MyPage.jsx
- 디자인이 아직 수정됨에 따라 계속 수정중입니다. ...
- 아직 끝 아니고 계속 수정해야 할 것 입니다 일단 봐주세요ㅠ
=> 💄 친구 리스트 페이지 대폭 수정

src/components/Main/Interview/TodayInterview.jsx, src/pages/Landing/LandingPage.jsx, src/pages/Main/MainPage.jsx, src/styles/GlobalStyle.js
=> 💄 fix: 짜치는 부분 수정

src/components/Main/Interview/FailModal.jsx, src/components/Main/Interview/SendQuestionModal.jsx
=> 🐛 fix: 모달 닫히는거 수정

src/components/ReplyQuestion/QuestionAllForm.jsx
=> 받은 인터뷰 블러처리 수정

src/api/axios.jsx, src/styles/GlobalStyle.js
=> 🐛 fix: 토큰 없으면 로그인으로

src/components/ReplyQuestion/ReplyModal.jsx
=> 🐛 fix: 모달 위치 수정
